workflows:
  ios:
    name: iOS Build
    environment:
      flutter: stable
    scripts:
      - name: Build iOS app
        script: flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.ipa

